// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fHporgW73aX9dnj1TlFXay2rt-dUSYQ',
    appId: '1:1001671561644:web:cdf2ee8eff4081db796a09',
    messagingSenderId: '1001671561644',
    projectId: 'diet-46cb7',
    authDomain: 'diet-46cb7.firebaseapp.com',
    storageBucket: 'diet-46cb7.firebasestorage.app',
    measurementId: 'G-DXZ99S0WML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwNispBFBU8FoliySjst_BWmRn-dWooE',
    appId: '1:1001671561644:android:c1419075c5a35388796a09',
    messagingSenderId: '1001671561644',
    projectId: 'diet-46cb7',
    storageBucket: 'diet-46cb7.firebasestorage.app',
  );

}